### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by sgerrand** [projectatomic/dockerfile_lint#112]
There's an important update in #108 which adds support for named references (i.e. `AS`) to `FROM` directive linting, which would enable linting for multi-stage `Dockerfile`s. It's been languishing seeking review from this project's maintainers since April of this year.

👋 @lphiri, are you still this project's maintainer?

**Comment by lphiri** [comment]
@sgerrand  Yes.
Temporarily lost admin access to the project but now can merge PRs.

**Comment by sgerrand** [comment]
Oh, great. Thanks!
