### ISSUE TITLE
Add JUnit XML format support

### ISSUE THREAD

**Issue by nightwatchcyber** [projectatomic/dockerfile_lint#141]
Wanted to recommend adding support for the JUnit XML format as an output option. This is needed because some CI/CD tools support it out of the box.

I had provided a pull request (#140) with the changes and unit tests for your review

**Comment by nightwatchcyber** [comment]
@lphiri Thank you for accepting the pull req. 

Are there any plans to release a new version on NPM? The last release was 0.3.3 back in 2018.

**Comment by lphiri** [comment]
@nightwatchcyber pushed a new release.

**Comment by nightwatchcyber** [comment]
Thanks!
