### ISSUE TITLE
npm install fails on enhanced_label_rule_support branch

### ISSUE THREAD

**Issue by dav1x** [projectatomic/dockerfile_lint#17]
Looks like the extendify addition is causing some issues:

npm ERR! git clone ssh://git@github.com/lphiri/extendify.git Cloning into bare repository '/root/.npm/_git-remotes/ssh-git-github-com-lphiri-extendify-git-16889689'...
npm ERR! git clone ssh://git@github.com/lphiri/extendify.git 
npm ERR! git clone ssh://git@github.com/lphiri/extendify.git Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
npm ERR! git clone ssh://git@github.com/lphiri/extendify.git Permission denied (publickey).
npm ERR! git clone ssh://git@github.com/lphiri/extendify.git fatal: Could not read from remote repository.
npm ERR! git clone ssh://git@github.com/lphiri/extendify.git 
npm ERR! git clone ssh://git@github.com/lphiri/extendify.git Please make sure you have the correct access rights
npm ERR! git clone ssh://git@github.com/lphiri/extendify.git and the repository exists.
npm ERR! Error: Command failed: Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/git2/dockerfile_lint
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/git2/dockerfile_lint/npm-debug.log
npm ERR! not ok code 0

I went ahead and changed the package.json to point to the regular registry:
"extendify": "git+ssh://git@github.com/lphiri/extendify.git",
to
"extendify": "1.0.0",

I'm not sure if you need a specific version. But upon the new build, i get various errors:

-> bin/dockerfile_lint -f Dockerfile -r sample_rules/label_rules.yaml 
/Users/dphillip/git/dockerfile_lint/lib/linter-utils.js:22
            rule.exists = false;
                        ^
TypeError: Cannot assign to read only property 'exists' of LABEL

and 

/root/git2/dockerfile_lint/lib/linter-utils.js:165
            if (rules[i].hasOwnProperty(stripQuotes(key))) {
                         ^
TypeError: Cannot call method 'hasOwnProperty' of undefined

**Comment by lphiri** [comment]
The linter depends on an update to extendify that is not officially released yet. I will push a temporary workaround later this evening. In the meantime you can apply the patch [1] to extendify in the node modules directory.

[1] https://github.com/bigShai/extendify/commit/ddca38ef8ce2211199074c3ba50b4b28fb3afe67

**Comment by lphiri** [comment]
Temporarily fixed this issue by removing github dependency.  Please re-run "npm install".
Check that everything is ok by running "npm test".

**Comment by dav1x** [comment]
Perfect. Patch and new version both work great! Thanks!
