### ISSUE TITLE
Write a complete default rule file

### ISSUE THREAD

**Issue by lphiri** [projectatomic/dockerfile_lint#21]
Current default rule file only checks Dockerfile syntax. Provide a rule file  that includes more best practices.

**Comment by dav1x** [comment]
I'm in the process of writing a default ruleset that looks at labels and some best practices on the dockerfile. This will be the first ruleset I work on. There will be more rulesets for atomic specifically and OSBS as well.

**Comment by lphiri** [comment]
@dav1x 
Great! When I was designing the rule profile specification  I  briefly looked at  [1,2,3] (assuming you have not come across them already). There is some overlap with what you have done already, but a few other  interesting checks that may be relevant . Might be worth taking a look to compare with what you are working on.

[1]https://github.com/lukasmartinelli/hadolint/blob/master/src/Rules.hs
[2]https://github.com/lukasmartinelli/hadolint/wiki
[3]https://github.com/RedCoolBeans/dockerlint/blob/master/src/checks.coffee

**Comment by lphiri** [comment]
@dav1x  - also let me know if any rules are too hard to implement with the current yaml spec. One thing I think my help, for special cases is to bake checks into the code, and just have the rule file turn the checks on or off.

**Comment by dav1x** [comment]
@lphiri Thank you for the share! I'm going through the ruleset in an effort to add to our own.

**Comment by dav1x** [comment]
I have largely finished the basic_rules.yaml. Would you like me to put this in place of the current base rules in the /dockerfile_lint/config directory?

**Comment by lphiri** [comment]
@dav1x  - since your base rule file has some atomic specific rules - how about we do that after we update the linter to support "profiles' that would select the correct rule set? That would allow  us to use your base rule file as default while allowing non atomic users to run a different base rule set.  I have some done some of the work for this already.

**Comment by dav1x** [comment]
@lphiri It would be pretty easy for me to modify the base ruleset and just filter out the stuff like the atomic specific labels. 

It's up to you!

**Comment by lphiri** [comment]
@dav1x  in that case go ahead and merge!

**Comment by dav1x** [comment]
@lphiri I added the default templates but, im noticing some automated testing errors. 

I modified the lib/rulefile-load.js to establish a base default template if no path is given


  if (!ruleFilePath) {
	ruleFilePath = "config/default_rules.yaml"
  }

Then we could probably just remove the else statement and let the rest of the code process with the default ruleset. The problem is the automated testing fails with against the warning or error level dockerfiles in ./test/. Let me know if you want me to modify the added default templates in ./config/ to pass the tests. 

Thanks and have a great weekend!

**Comment by lphiri** [comment]
@dav1x  - I am ok with you modifying the tests work with the default rule file  with your suggested changes above.

I would suggest you make the testcases pass by adding  "-r config/base_rules.yml"  as appropriate.

I think it would be useful to have a syntax checking only mode (via a commandline option), which would make the linter behave the same way it did before (i.e just use the base rules file as above ), but  we can add the commandline switch later.
