### ISSUE TITLE
Add in debug option that flattens includes

### ISSUE THREAD

**Issue by dav1x** [projectatomic/dockerfile_lint#27]
Currently, functionality that allows for nested includes inside the base rules set as such:

includes: another-yaml-file.yaml

We would like functionality added that flattens all the input rules lists to a single file to simply in case of debugging. Additionally, the flattened file should also add in a single variable if multiples were detected in multiple files. For example, VendorName is a listed value in 2 different files. The accepted value should be the when included in the flattened output file. 

Thank you!

**Comment by lphiri** [comment]
Just need some clarification - are you asking that we dump the "effective" rule file in this case?
Is it sufficient to dump the file to the console?  - like this:

debug: Rule directory is sample_rules
debug: loading rule profile basic_rules.yaml
debug: rule file basic_rules.yaml has no includes
debug: Number of rule files found for basic_rules.yaml 1
debug: Effective rule set is :
profile:
  name: Default
  description: Default Profile. Checks basic syntax.
general:
  ref_url_base: "https://docs.docker.com/reference/builder/"
  valid_instructions:
    - FROM
    - MAINTAINER
    - RUN
    - CMD
    - LABEL
    - EXPOSE
    - ENV
    - ADD
    - COPY
    - ENTRYPOINT
    - VOLUME
    - USER
    - WORKDIR
    - ONBUILD
    - ARG
    - STOPSIGNAL
  ignore_regex: "/^#/"
  multiline_regex: "/\\\\$/"
line_rules:
  ARG:
    paramSyntaxRegex: /.+/
    rules: []
  FROM:
    paramSyntaxRegex: "/^[a-z0-9./-]+(:[a-z0-9.]+)?$/"
    rules:
      - label: is_latest_tag
        regex: /latest/
        level: info
        message: "base image uses 'latest' tag"
        description: "using the 'latest' tag may cause unpredictable builds. It is recommended that a specific tag is used in the FROM line."
        reference_url:
          - "https://docs.docker.com/reference/builder/"
          - "#from"
      - label: no_tag
        regex: "/^[:]/"
        level: warn
        message: No tag is used
        description: lorem ipsum tar
        reference_url:
          - "https://docs.docker.com/reference/builder/"
          - "#from"
  MAINTAINER:
    paramSyntaxRegex: /.+/
    rules: []
  RUN:
    paramSyntaxRegex: /.+/
    rules:
      - label: no_yum_clean_all
        regex: "/yum ((?!clean all).)* .+/"
        level: warn
        message: yum clean all is not used
        description: the yum cache will remain in this layer making the layer unnecessarily large
        reference_url: None
      - label: installing_ssh
        regex: /ssh/
        level: warn
        message: installing SSH in a container is not recommended
        description: Do you really need SSH in this image?
        reference_url: "https://github.com/jpetazzo/nsenter"
  CMD:
    paramSyntaxRegex: /.+/
    rules: []
  LABEL:
    paramSyntaxRegex: /.+/
    rules: []
  EXPOSE:
    paramSyntaxRegex: "/^[0-9]+([0-9\\s]+)?$/"
    rules: []
  ENV:
    paramSyntaxRegex: "/^[a-zA-Z_]+[a-zA-Z0-9_]* .+$/"
    rules: []
  ADD:
    paramSyntaxRegex: "/^(~?[A-z0-9\\/_.-]+|https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&\\/\\/=]*))\\s~?[A-z0-9\\/_.-]+$/"
  COPY:
    paramSyntaxRegex: /.+/
    rules: []
  ENTRYPOINT:
    paramSyntaxRegex: /.+/
    rules: []
  VOLUME:
    paramSyntaxRegex: /.+/
    rules: []
  USER:
    paramSyntaxRegex: "/^[a-z_][a-z0-9_]{0,30}$/"
    rules: []
  WORKDIR:
    paramSyntaxRegex: "/^~?[A-z0-9\\/_.-]+$/"
    rules: []
  ONBUILD:
    paramSyntaxRegex: /.+/
    rules: []
required_instructions:
  MAINTAINER:
    instruction: MAINTAINER
    count: 1
    level: info
    message: Maintainer is not defined
    description: "The MAINTAINER line is useful for identifying the author in the form of MAINTAINER Joe Smith <joe.smith@example.com>"
    reference_url:
      - "https://docs.docker.com/reference/builder/"
      - "#maintainer"
  EXPOSE:
    instruction: EXPOSE
    count: 1
    level: info
    message: "There is no 'EXPOSE' instruction"
    description: Without exposed ports how will the service of the container be accessed?
    reference_url:
      - "https://docs.docker.com/reference/builder/"
      - "#expose"
  ENTRYPOINT:
    instruction: ENTRYPOINT
    count: 1
    level: info
    message: "There is no 'ENTRYPOINT' instruction"
    description: None
    reference_url:
      - "https://docs.docker.com/reference/builder/"
      - "#entrypoint"
  CMD:
    instruction: CMD
    count: 1
    level: info
    message: "There is no 'CMD' instruction"
    description: None
    reference_url:
      - "https://docs.docker.com/reference/builder/"
      - "#cmd"
  USER:
    instruction: USER
    count: 1
    level: warn
    message: "No 'USER' instruction"
    description: The process(es) within the container may run as root and RUN instructions my be run as root
    reference_url:
      - "https://docs.docker.com/reference/builder/"
      - "#user"
discouraged_instructions: []
mutually_exclusive_instructions: []

**Comment by aweiteka** [comment]
It might be better to have a no-op `--export-flattened-ruleset` (or something) option to stdout. This could be piped to a file, edited, reviewed, passed in as a rule file, test, etc.

**Comment by aweiteka** [comment]
@lphiri sorry, it looks like that's what you were suggesting. :)

**Comment by lphiri** [comment]
@aweiteka  - its almost what I was suggesting :) . I was suggesting dumping the rule file as part of existing standard debug (without the no-op option).  It would be very easy to add a no-op version though - 
something like "dockefile_lint --export-rules -r  rule-with-includes.yaml"
