### ISSUE TITLE
Defined_namevals case sensitive

### ISSUE THREAD

**Issue by dav1x** [projectatomic/dockerfile_lint#36]
A defined label in a dockerfile that is defined as 

LABEL name 
will only match if the line is listed as below:

 defined_namevals:
           name:
             valueRegex: /([\w]+)./

If the LABEL Name is used; the linter will throw an error about missing label. 

Can we cast the value into upper or lower before matching the line to allow for either variation before the regex match starts?

**Comment by lphiri** [comment]
Sounds reasonable.  Case sensitivity may matter for ENV, so I would suggest we default to being case insensitive, but add a switch to allow for case sensitive checks.

**Comment by dav1x** [comment]
@lphiri Agreed 100% Thanks for being so quick on the pick up!
