### ISSUE TITLE
Wrong regex for USER instruction (rulefiles)

### ISSUE THREAD

**Issue by scr4bble** [projectatomic/dockerfile_lint#43]
Regular expressions for USER instructions do not support passing USER ID instead of username:
https://docs.docker.com/engine/reference/builder/#user

https://github.com/projectatomic/dockerfile_lint/blob/master/sample_rules/basic_rules.yaml#L139
https://github.com/projectatomic/dockerfile_lint/blob/master/config/default_rules.yaml#L65

**Comment by dav1x** [comment]
@scr4bble Submit update to resolve this issue 

https://github.com/projectatomic/dockerfile_lint/pull/44/files

Thanks!
