### ISSUE TITLE
FROM basic rules

### ISSUE THREAD

**Issue by caduvieira** [projectatomic/dockerfile_lint#53]
Before https://github.com/projectatomic/dockerfile_lint/blob/master/sample_rules/basic_rules.yaml#L87
and https://github.com/projectatomic/dockerfile_lint/blob/master/sample_rules/basic_rules.yaml#L95

shouldn't be another item "-"?

And in https://github.com/projectatomic/dockerfile_lint/blob/master/sample_rules/basic_rules.yaml#L102

is the correct '#from' ?

**Comment by dav1x** [comment]
@caduvieira No, the -'s emphasis the lists. In the default rules:

https://github.com/projectatomic/dockerfile_lint/blob/master/config/default_rules.yaml

You can see the same listed format for building the URI.
https://github.com/projectatomic/dockerfile_lint/blob/master/sample_rules/basic_rules.yaml#L230-L232

Here is sample output from the parser:
INFO: There is no 'EXPOSE' instruction. Without exposed ports how will the service of the container be accessed?. 
Reference -> https://docs.docker.com/reference/builder/#expose

It is working as designed.

**Comment by caduvieira** [comment]
Ok thank you
