### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'config/default_rules.yaml'

### ISSUE THREAD

**Issue by rarkins** [projectatomic/dockerfile_lint#54]
I am using `dockerfile_lint` as part of a Docker image I've built for all-in-one linting: https://github.com/singapore/lint-condo

Because of the project itself being a Docker image, I am using the `npm` version of your library.

I've experienced a confusing failure when upgrading from 0.2.2 to 0.2.3 in this PR: https://github.com/singapore/lint-condo/pull/88

As above, the error is:
```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'config/default_rules.yaml'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at loadRuleFile (/node_modules/dockerfile_lint/lib/rulefile-loader.js:34:27)
    at load (/node_modules/dockerfile_lint/lib/rulefile-loader.js:74:9)
    at new Linter (/node_modules/dockerfile_lint/lib/linter.js:64:18)
    at lint (/node_modules/dockerfile_lint/bin/dockerfile_lint:84:25)
    at lintDockerFile (/node_modules/dockerfile_lint/bin/dockerfile_lint:104:9)
    at Object.<anonymous> (/node_modules/dockerfile_lint/bin/dockerfile_lint:144:5)
    at Module._compile (module.js:410:26)
```

The command run was simply: `dockerfile_lint -f Dockerfile`

I don't see any note about a breaking change in 0.2.3 or that a config file is mandatory in your README. perhaps your default config yaml files got left out of the npm package or something like that? I don't mind adding a config file if it's a new requirement but I've got a feeling that this wasn't intentional.

**Comment by lphiri** [comment]
Thanks for reporting. This is a bug - will push a new version out as soon as its fixed.

**Comment by dav1x** [comment]
@lphiri I think I caused this. I can correct it when I get home next week. It's a relative pathing issue with the default config file being specified.

**Comment by lphiri** [comment]
@dav1x cool. i will publish a new npm version once you have fixed issue.

**Comment by osvalr** [comment]
confirming this is happening to me as well

**Comment by SanketDG** [comment]
Bump @dav1x

**Comment by lphiri** [comment]
@dav1 publishing a patch since its a simple one(i think).

**Comment by lphiri** [comment]
https://github.com/projectatomic/dockerfile_lint/commit/2c9e1178ad7e507b8e1d8af7a8e280e131d0c4c6
