### ISSUE TITLE
TypeError: helper.or is not a function

### ISSUE THREAD

**Issue by chrisdias** [projectatomic/dockerfile_lint#59]
if the LABEL command is poorly formatted, get TypeError in lib/linter.js, line 27

``` javascript
function validateCommand(command, context, result) {
    if (command.error) {
        helper.or(result, command.lineno, command.raw, command.error,null);
    }
```

i think it should be addError:

``` javascript
helper.addError(result, command.lineno, command.raw, command.error,null);
```

To reproduce this issue, simply put the following in a dockerfile and run dockerfile_lint:

LABEL Nam

**Comment by lphiri** [comment]
@chrisdias - you are correct. This is already fixed in a private branch. Will push it soon!
