### ISSUE TITLE
--json emits non-json in 0.2.5

### ISSUE THREAD

**Issue by jayvdb** [projectatomic/dockerfile_lint#66]
We have only started to investigate a potential breakage that has occurred only within the last two days.

https://github.com/coala/docker-coala-base/issues/89

**Comment by lphiri** [comment]
@jaydb - Could you please provide more information on what is failing? I cant tell from the linked issue

**Comment by jayvdb** [comment]
Our [bad_file](https://github.com/coala/coala-bears/blob/master/tests/configfiles/DockerfileLintBearTest.py#L18) is not generating any errors.

**Comment by lphiri** [comment]
I see errors when I run against the bad file as expected (using latest dockerfile_lint 0.2.5).
Looks like a console log message was left in the latest code by mistake , so the output is not valid json. Is that possibly confusing your tests?

Here is what i see in my terminal:
 dockerfile_lint -f ~/docker_test --json
Invalid Dockerfile command: APT-GET
Invalid Dockerfile command: APT-GET
{
  "error": {
    "count": 6,
    "data": [
      {
        "message": "Invalid Command",
        "line": 3,
        "level": "error",
        "lineContent": "apt-get -y -qq update",
        "reference_url": "https://docs.docker.com/reference/builder/"
      },
      {
        "message": "Invalid instruction",
        "line": 3,
        "level": "error",
        "lineContent": "apt-get -y -qq update",
        "reference_url": "https://docs.docker.com/reference/builder/"
      },
      {
        "message": "Invalid Command",
        "line": 4,
        "level": "error",
        "lineContent": "apt-get -y -qq upgrade",
        "reference_url": "https://docs.docker.com/reference/builder/"
      },
      {
        "message": "Invalid instruction",
        "line": 4,
        "level": "error",
        "lineContent": "apt-get -y -qq upgrade",
        "reference_url": "https://docs.docker.com/reference/builder/"
      },
      {
        "message": "Required LABEL name/key 'Name' is not defined",
        "line": -1,
        "level": "error",
        "lineContent": "",
        "reference_url": [
          "http://docs.projectatomic.io/container-best-practices/#",
          "_recommended_labels_for_your_project"
        ]
      },
      {
        "message": "Required LABEL name/key 'Version' is not defined",
        "line": -1,
        "level": "error",
        "lineContent": "",
        "reference_url": [
          "http://docs.projectatomic.io/container-best-practices/#",
          "_recommended_labels_for_your_project"
        ]
      }
    ]
  },
  "warn": {
    "count": 0,
    "data": []
  },
  "info": {
    "count": 2,
    "data": [
      {
        "instruction": "EXPOSE",
        "count": 1,
        "level": "info",
        "message": "There is no 'EXPOSE' instruction",
        "description": "Without exposed ports how will the service of the container be accessed?",
        "reference_url": [
          "https://docs.docker.com/reference/builder/",
          "#expose"
        ]
      },
      {
        "instruction": "CMD",
        "count": 1,
        "level": "info",
        "message": "There is no 'CMD' instruction",
        "description": "None",
        "reference_url": [
          "https://docs.docker.com/reference/builder/",
          "#cmd"
        ]
      }
    ]
  },
  "summary": []
}

**Comment by jayvdb** [comment]
Ya,we use`--json`, so invalid json will be the cause.

**Comment by lphiri** [comment]
@jayvdb pushed a new version of the linter - should fix your issue.

**Comment by jayvdb** [comment]
Yup; fixed in 0.2.6.  Thanks
