### ISSUE TITLE
FROM

### ISSUE THREAD

**Issue by sandersky** [projectatomic/dockerfile_lint#70]
The regex `/^[\\w./-:]+(:[\\w.]+)?(-[\\w.]+)?$/` actually treats `/-:` as a range instead of 3 different characters. Instead It should be something like `/^[\\w-./:]+(:[\\w.]+)?(-[\\w.]+)?$/`.

**Comment by dav1x** [comment]
Nice catch @sandersky 

Instead, lets escape the character to get the - in the FROM line. 
```
^[\\w./\-:]+(:[\\w.]+)?(-[\\w.]+)?$
```
