### ISSUE TITLE
Support multiple rules files

### ISSUE THREAD

**Issue by alvin-huang** [projectatomic/dockerfile_lint#76]
Is there a way to include multiple rules files such as `-r /rules/ruleset1.yaml /rules/ruleset2.yaml`? I think this would be useful if I wanted to add some custom rules for my organization that are in addition to the default ruleset for example. 

If not, would this be a feature that other people would be interested in?

**Comment by lphiri** [comment]
@alvin-huang . That sounds like a reasonable use case.  You can achieve a similar effect by  including any number of rule files inside another rule file by adding an "includes" directive in the profile section of the ruleset you want to extend :

 ---
  profile:
    name: "Base rule"
    description: "Default Profile. Checks basic syntax."
    includes:
        - another_rule_file.yaml
        - yet_another_rule_file.yaml

**Comment by alvin-huang** [comment]
That could work for me.

While digging through the code however, I noticed: https://github.com/projectatomic/dockerfile_lint/blob/master/test/data/rules/loader_test_combine_main.expected.json#L41

Is this intended? Is the `paramSyntaxRegex` not overwritten by `file2`? Are just the `rules` merged and not the `paramSyntaxRegex`? 

This may just be a crude use case that may not be used but lets say we have a `company.docker.registry` as well as `myteam.docker.registry`. Let say I allow people to use images `FROM` either of those and the `company_linter.yaml` has a regex that allows for `/company\.docker\.registry.*/` while `myteam_linter.yaml` has a regex that allows `/myteam\.docker\.registry.*/`. If I `includes` both files in my test for my team and a colleague uses a docker image from myteam's registry. Currently, that would throw an error correct? Shouldn't it merge the two regexes?

**Comment by lphiri** [comment]
The linter does not merge string or regex values (we override instead) since we can't do this reliably in code . You will have to merge these yourself. Note that the order of the includes is important - the matches for overrides are done in reverse order i.e.  look in the including file, then the first listed include, then the second etc.

**Comment by alvin-huang** [comment]
So you're saying in the link above, the section of
```
    includes:
        - loader_test_combine_1.yaml
        - loader_test_combine_2.yaml
```
means it will load `/file2/` first and then gets overridden by `/file1/`?

**Comment by lphiri** [comment]
Sorry - ignore the word "reverse" in my previous post should say "the matches for overrides are done in order of inclusion", so file2 will load first and then be overridden by file1.

**Comment by lphiri** [comment]
closing since the includes function satisfies your requirement.
