### ISSUE TITLE
JSON Object Breaks due to console.log

### ISSUE THREAD

**Issue by nvzard** [projectatomic/dockerfile_lint#97]
JSON object returned by using --json flag is not clean due to the console.log on line :- https://github.com/projectatomic/dockerfile_lint/blob/15d5841774bc4986690a46d2795cf849d41429ab/bin/dockerfile_lint#L74

**Comment by lphiri** [comment]
@Lucas-C  can you take a look?  I can just delete the offending log.

**Comment by nvzard** [comment]
I am not able to parse JSON easily due to this problem.
While parsing using `json.loads(output)` it raises
```
json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)
```

**Comment by Lucas-C** [comment]
I've sent a PR to fix this

**Comment by nvzard** [comment]
Thanks a lot, @lphiri and @Lucas-C for your support, much appreciated :+1:
